### ISSUE TITLE
Using the ProgressLogger with Rayon

### ISSUE THREAD

**Issue by progval** [vigna/dsi-progress-logger-rs#3]
Hi,

A pattern I find myself reusing when working with Rayon is the following:

```rust
            let mut pl = ProgressLogger::default().display_memory();
            pl.item_name = "arc";
            pl.local_speed = true;
            pl.expected_updates = Some(estimate_updates(&dataset_dir));
            pl.start("Sorting arcs");
            let pl = Mutex::new(pl);

            let counters = thread_local::ThreadLocal::new();
            let sorted_arc_lists: Vec<SortPairs<()>> = iter_arcs(&dataset_dir)
                .inspect(|_| {
                    // This is safe because only this thread accesses this and only from
                    // here.
                    let counter = counters.get_or(|| UnsafeCell::new(0));
                    let counter: &mut usize = unsafe { &mut *counter.get() };
                    *counter += 1;
                    if *counter % 32768 == 0 {
                        // Update but avoid lock contention at the expense
                        // of precision (counts at most 32768 too many at the
                        // beginning of each iterator)
                        pl.lock().unwrap().update_with_count(32768);
                        *counter = 0
                    }
                })
                .map(|arc| {
                    // ...
                })
                .collect();
```

Is this something you think is worth documenting in this crate?

**Comment by vigna** [comment]
I'm puzzled by the comment—since you increment the counter before the check, you won't update until 32767 iterations have been completed, right?

Well, this is the same pattern I use, but since we've been starting our threads until now it's simpler because you can use local variables. Tommaso has a PR with a concurrent progress logger but it has a few problems.

Note that for precise measuring you'll need to call `done_with_count` afterwards as you might miss a few updates (at most 32767 multiplied by the number of threads, I guess).

I am a bit wary of suggesting this pattern as it is because `get_or` does some work (with atomics). If iteration is not too fast this is going to be negligible, but not in general. But we could explain it.

Maybe we could provide a macro depending on pl for the `inspect` part. What do you think?

**Comment by progval** [comment]
> I'm puzzled by the comment—since you increment the counter before the check, you won't update until 32767 iterations have been completed, right?

Indeed, my bad. I probably have variations of this pattern where I increment after somewhere, too...

> Note that for precise measuring you'll need to call done_with_count afterwards

Indeed. I'd need to add this at the end of the pipeline (in terms of code layout); not great if the pipeline is long.

> Maybe we could provide a macro depending on pl for the inspect part. What do you think?

What would it look like?

**Comment by vigna** [comment]
I mean a macro for the `inspect` part only. You'd still to have to get the mutex and call `done_with_count` at the end. But that can be explained, and it's not too much.
